name: Feature Completion & Merge Request
description: Request to merge a completed feature into the main branch.
title: "[Feature Completed]: "
labels: ["feature-completed", "ready-for-review"] # Added 'feature-completed' and 'ready-for-review'
projects: []
assignees: [] # Assign to code reviewers or team leads here

body:
  - type: markdown
    attributes:
      value: |
        Thanks for completing this feature! Please fill out the following details to facilitate a smooth review and merge process.

        ---

  - type: input
    id: related-design-issue
    attributes:
      label: Related Feature Design Issue(s)
      description: Link to the original feature design issue(s) this work completes (e.g., #123, #456).
      placeholder: "e.g., #123"
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Briefly describe what was implemented in this feature.
      placeholder: "Implemented user profile editing, allowing users to update their name, email, and avatar."
    validations:
      required: true

  - type: textarea
    id: changes-made
    attributes:
      label: Detailed Changes Made
      description: List the key changes, components, or files involved. What specific tasks from the design issue were addressed?
      placeholder: |
        - Added `UserProfileService` for API calls.
        - Implemented `ProfileEditor` React component.
        - Updated `users` table schema with new fields.
        - ...
    validations:
      required: true

  - type: textarea
    id: how-to-test
    attributes:
      label: How to Test (Manual Testing Steps)
      description: Provide clear, step-by-step instructions on how to manually test this feature to verify its functionality.
      placeholder: |
        1. Log in as a regular user.
        2. Navigate to /settings/profile.
        3. Change username to "TestUser" and click Save.
        4. Verify success message and updated username.
    validations:
      required: true

  - type: checkboxes
    id: automated-tests
    attributes:
      label: Automated Tests
      description: Indicate which types of automated tests have been added or updated for this feature.
      options:
        - label: Unit Tests (e.g., Jest, JUnit)
        - label: Integration Tests (e.g., React Testing Library, Supertest)
        - label: End-to-End (E2E) Tests (e.g., Cypress, Playwright)
        - label: No new/updated automated tests (Please explain why below if this is the case)
    validations:
      required: false

  - type: textarea
    id: testing-notes
    attributes:
      label: Testing Notes / Rationale (if no automated tests)
      description: Provide any additional notes about testing, or explain why no automated tests were added/updated for this specific feature.
      validations:
        required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Reviewer Checklist
      description: Before requesting review, please ensure you've checked these items.
      options:
        - label: My code follows the project's coding style guidelines.
        - label: I have performed a self-review of my own code.
        - label: My changes pass all existing automated tests.
        - label: My changes introduce no new warnings or errors.
        - label: I have updated relevant documentation (e.g., API docs, user guides) if necessary.
        - label: I have considered potential security implications.
        - label: I have considered performance implications.
        - label: This feature works as described in the acceptance criteria of the design issue.
          required: true
    validations:
      required: true

  - type: textarea
    id: deployment-notes
    attributes:
      label: Deployment Notes (Optional)
      description: Are there any specific deployment instructions, environment variables, or post-deployment steps required for this feature?
      validations:
        required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true